apiVersion: apps/v1
kind: Deployment
metadata:
  name: land-devops-deployment
spec:
  replicas: 10
  strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 10%
          maxUnavailable: 10%
  selector:
    matchLabels:
      app: land-devops
  template:
    metadata:
      labels:
        app: land-devops
    spec:
      containers:
        - name: land-devops
          image: vakadev/land_devops:v1.4.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
    