name: Version update and deploy to Docker pipeline

on: 
  pull_request:
    types: [closed]
    branches:
    - feature/test-workflow
  workflow_dispatch: 


jobs:
  pre-merge-check:
    name: (INF) Log Info
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Log Info
        id: log-info
        run: |
          echo "EVENT NAME    : ${{ github.event_name }}"
          echo "CURRENT BRANCH: ${{ steps.branch-names.outputs.current_branch }}"
          echo "REF NAME      : ${{ github.ref_name }}"


  security:
    name: (SEC) Security
    needs: pre-merge-check
    uses: vakaheydev/land_devops/.github/workflows/security.yml@feature/change-workflow

  tests:
    name: (TST) Test
    needs: security
    uses: vakaheydev/land_devops/.github/workflows/test.yml@feature/change-workflow
    with:
      version: alpha

  update-version:
    name: (VER) Version UP
    uses: vakaheydev/land_devops/.github/workflows/update-version.yml@feature/change-workflow
    needs: tests
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

  build:
    name: (BUILD) Build application
    needs: update-version
    uses: vakaheydev/land_devops/.github/workflows/build.yml@feature/change-workflow
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write


  docker:
    name: (CI) Docker push 
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    runs-on: ubuntu-latest
    needs: [build,update-version]
    env: 
      tag: ${{needs.update-version.outputs.tag}}

  