name: Version update pipeline

on: 
  pull_request:
    types: [closed]
    branches:
    - release
    - main
env:
  NAME_VERSION_FILE: version
jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: pasrse data
        id: parse-data
        uses: tj-actions/branch-names@v8

      - name: Print info about actions
        run: |
          echo "EVENT NAME: ${{ github.event_name }}"
          echo "CURRENT BRANCH: ${{ steps.parse-data.outputs.current_branch }}"
          echo "DEFAULT BRANCH: ${{ steps.parse-data.outputs.default_branch }}"
          echo "OUTPUTS: ${{ steps.parse-data.outputs }}"
  print-data-information:
    runs-on: ubuntu-latest
    steps:
      - name: Second step
        run: echo "Print info"
      - name: 3 step
        run: echo "Print info"
    
